split vars uptime/linkuptime
mcktr/check_tr64_fritz pull request #23
Opened 2017-10-17 16:09 UTC by cxcv

icinga relies on unique vars when values are exposed to influxdb, this we need to split this

2017-10-17 18:39 UTC, mcktr commented on check_tr64_fritz
> +    echo "OK - Link Uptime ${LINKUPTIME} seconds (${days}d ${hours}h ${minutes}m ${seconds}s) | uptime=${LINKUPTIME}"
Don't we need to change the performance data metric as well?

2017-10-17 18:40 UTC, mcktr requested changes
Please change the performance data metric as well, this should be the main issue here.

2017-10-18 08:54 UTC, cxcv commented
I've missed that, it's fixed and tested now.

2017-10-18 18:20 UTC, mcktr approved these changes

2017-10-18 18:24 UTC, mcktr commented
Thanks! :+1: 

Before merging I squashed your commits into a single commit.

2017-10-18 18:24 UTC, merged